### ISSUE TITLE
How do I compile this for Linux?

### ISSUE THREAD

**Issue by ElonSatoshi** [iammeat/POSTAL-1-Open-Source#1]

**Comment by iammeat** [comment]
I've only set this up as a GitHub mirror.  For discussions about the building process, please check out the main repository over at BitBucket here:

https://bitbucket.org/gopostal/postal-1-open-source

**Comment by iammeat** [comment]
This game was ported previously to a version of Linux for the Pandora handheld device.

https://pyra-handheld.com/boards/threads/postal.77565/
